
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/xHeptc/Kavo-UI-Library/main/source.lua"))()
local Window = Library.CreateLib("Dead rails best hubs owner Amonrus_pro777", "DarkTheme")
local Tab = Window:NewTab("Dead rails hubs")
local Section = Tab:NewSection("Dead rails")
Section:NewButton("Than hub(no key)", "ButtonInfo", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/thantzy/thanhub/refs/heads/main/thanv1"))()
    print("Clicked")
end)
Section:NewButton("Skullhub(keyless)", "ButtonInfo", function()
loadstring(game:HttpGet('https://raw.githubusercontent.com/hungquan99/SkullHub/main/loader.lua'))()
    print("Clicked")
end)
Section:NewButton("Speed hub(no key maybe) ", "ButtonInfo", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/AhmadV99/Speed-Hub-X/main/Speed%20Hub%20X.lua", true))()
    print("Clicked")
end)
Section:NewButton("Nullfire(no key)", "ButtonInfo", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/InfernusScripts/Null-Fire/main/Loader"))()
    print("Clicked")
end)
Section:NewButton("Legend hub(keyless)", "ButtonInfo", function()
loadstring(game:HttpGet("https://scripts.city/LegendHub.lua"))()
    print("Clicked")
end)
Section:NewButton("Solixhub (keyless)", "ButtonInfo", function()
loadstring(game:HttpGet("https://raw.githubusercontent.com/debunked69/Solixreworkkeysystem/refs/heads/main/solix%20new%20keyui.lua"))()
    print("Clicked")
end)
Section:NewButton("Good hub(no key)", "ButtonInfo", function()
loadstring(game:HttpGet('https://github.com/Amonruspro777/DeadRailsNewAlphaGui/blob/main/Alpha%20gui.lua'))()
    print("Clicked")
end)